version: "3.8"
services:
  mysql:
    build: './database/mysql'
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_ROOT_USER=root
      - MYSQL_DATABASE=friends
    ports:
      - '3333:3306'
    restart: always
  mongo:
    build: './database/mongo'
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root 
      - MONGO_INITDB_ROOT_PASSWORD=secret 
      - MONGO_INITDB_DATABASE=colleagues
    ports:
      - '27017:27017'
    restart: always
  server:
    build: './server'
    ports: 
      - '250:500'
    container_name: server
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3333
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_ROOT_USER=root
      - MYSQL_DATABASE=friends
      - MONGO_HOSTNAME=mongo
      - MONGO_PORT=27017
      - MONGO_PASSWORD=secret 
      - MONGO_USERNAME=root 
      - MONGO_DB=colleagues 
    depends_on: 
      - mysql
      - mongo
    restart: always
    stdin_open: true
    tty: true
  client:
    build: './client'
    ports: 
      - '300:3000'
    container_name: client
    stdin_open: true
    tty: true
    depends_on: 
      - server
    restart: always